# Generated by Django 5.1.5 on 2025-02-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footballgame",
            name="away_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="footballgame",
            name="halftime_away_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="footballgame",
            name="halftime_home_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="footballgame",
            name="home_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
